clc;
clear;
close all;
n = 15;
k = 11;
data = randi([0 1],k,1);
disp("original meessage");
disp(data);
encData = encode(data,n,k,'hamming/binary');
disp('Encoded Message');
disp(encData);
errLoc = randerr(1,n);
encData_courrupted = mod(encData + errloc',2);
disp('Corrupted Encoded message:');
disp(encData_corrupted');
decData = decode(encData_corrupted,n,k,'hamming/binary');
disp(decData);
numerr = biterr(data,decData);
disp(['Number of bit errors Between Original and decoded message:',num2str(numerr)]);
